controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

access_denied:
    path: /access-denied
    controller: App\Controller\ErrorController::accessDenied